create table cinema
(
    id   int8 generated by default as identity,
    city varchar(255) not null,
    name varchar(255) not null,
    primary key (id)
);

create table hall
(
    id        int8 generated by default as identity,
    name      varchar(255) not null,
    cinema_id int8 not null,
    primary key (id)
);

create table movie
(
    id           int8 generated by default as identity,
    age_limit    varchar(255) not null,
    description  varchar(2048) not null,
    duration     int4 not null,
    image        varchar(255) not null,
    name         varchar(255) not null,
    release_year int4 not null,
    type         varchar(255) not null,
    primary key (id)
);

create table movie_genres
(
    movie_id int8 not null,
    genres   varchar(255) not null
);

create table movie_session
(
    id           int8 generated by default as identity,
    date         date not null,
    price        float8 not null,
    started_time time not null,
    cinema_id    int8 not null,
    hall_id      int8 not null,
    movie_id     int8 not null,
    primary key (id)
);

create table orders
(
    id               int8 generated by default as identity,
    movie_session_id int8 not null,
    seat_id          int8 not null,
    user_id          int8 not null,
    primary key (id)
);

create table seat
(
    id          int8 generated by default as identity,
    row         int4 not null,
    seat        int4 not null,
    seat_status varchar(255) not null,
    seat_type   varchar(255) not null,
    hall_id     int8 not null,
    primary key (id)
);

create table user_roles
(
    user_id int8 not null,
    roles   varchar(255) not null
);

create table users
(
    id       int8 generated by default as identity,
    age      int4         not null,
    email    varchar(255) not null,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

alter table if exists hall
    add constraint hall_cinema_fk foreign key (cinema_id) references cinema;

alter table if exists movie_genres
    add constraint movie_genres_movie_fk foreign key (movie_id) references movie;

alter table if exists movie_session
    add constraint movie_session_cinema_fk foreign key (cinema_id) references cinema;

alter table if exists movie_session
    add constraint movie_session_hall_id_fk foreign key (hall_id) references hall;

alter table if exists movie_session
    add constraint movie_session_movie_id_fk foreign key (movie_id) references movie;

alter table if exists orders
    add constraint orders_movie_session_id_fk foreign key (movie_session_id) references movie_session;

alter table if exists orders
    add constraint orders_seat_id_fk foreign key (seat_id) references seat;

alter table if exists orders
    add constraint orders_user_id_fk foreign key (user_id) references users;

alter table if exists seat
    add constraint seat_hall_id_fk foreign key (hall_id) references hall;

alter table if exists user_roles
    add constraint user_roles_user_id_fk foreign key (user_id) references users;